name: Deploy

on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
    
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Diagnostics
        run: |
          echo "Current Working Directory is: $PWD"
          ls -a # 這裡應該會看到 package.json

      - name: Install depemdemcoes and Build
        working-directory: ./ 
        run: |
          npm install
          npm run build

      - name: Stop pm2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user/action-test
            ls -la
            # pm2 stop ecosystem.config.js
            rm -fr .output

      - name: Sync Dis Files to AlmaLinux VM
        uses: burnett01/rsync-deployments@v8
        with:
          remote_host: ${{ secrets.GCP_VM_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

          path: ".output"
          remote_path: "/home/user/action-test/.output"
          debug: true
          switches: "-avz"
          

      - name: Copy to nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user/action-test
            ls
            # pm2 start ecosystem.config.js
        
  
    
